### ISSUE TITLE
run script `yarn dev`

### ISSUE THREAD

**Issue by fimars** [egoist/esbin#4]
![image](https://cloud.githubusercontent.com/assets/16299018/24533821/a4d5df96-15fc-11e7-80ef-531c7f131211.png)
Then the browser environment fails to run
Google Chrome: 版本 57.0.2987.133 (64-bit)
OS X: 10.10.5 (14F2109)
Node: v7.2.1
npm: v3.10.9
yarn.lock: https://gist.github.com/ChenZerong/3415cb70feb7498c4a686369d134ba2d

(... i want to add resize panel for esbin

**Comment by egoist** [comment]
open it with `yarn app`

**Comment by fimars** [comment]
![image](https://cloud.githubusercontent.com/assets/16299018/24534198/f0426e48-15fe-11e7-9eaf-b74fdbcfcd80.png)
so... what can i do now. @egoist  QAQ

**Comment by fimars** [comment]
i find https://github.com/egoist/codepan
